[build-system]
requires = ["setuptools >= 61.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages = [
    "yaml_ml",
    "yaml_ml.preprocessing",
    "yaml_ml.dataset",
    "yaml_ml.model",
    "yaml_ml.pipeline",
]

[tool.setuptools.package-data]
"yaml_ml" = ["modules.yaml"]

[project]
name = "yaml_ml"
version = "0.0.141"
authors = [
  {name="GFaure9"},
]
description = "Your whole ML pipeline in one YAML file."
readme = "short_description.md"
license = {file = "LICENSE.txt"}
requires-python = ">=3.11"
dynamic = ["dependencies"]
classifiers = [
    "Development Status :: 4 - Beta",
    "Programming Language :: Python :: 3.11",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Topic :: Scientific/Engineering :: Artificial Intelligence",
]

[tool.setuptools.dynamic]
dependencies = {file = ["requirements.txt"]}

[project.urls]
Repository = "https://github.com/GFaure9/yaml-ML"