logs: no

loading:
  folder: "C:/Users/guilh/Documents/Projets_Code/yaml-ML/datasets"
  name: "insurance_charges"
  format: 'csv'
  separator: ','

target_var: 'charges'

preprocessing:
  charges:
    type: "cont"
    cleaning: ['remove_nans', 'remove_outliers']
    replace_nans: 'median'
  age:
    type: "cont"
    cleaning: ['remove_nans', 'remove_outliers']
    replace_nans: 'most_frequent'
    scaling: 'abs_max'
  sex:
    type: "cat"
    cleaning: 'remove_nans'
    encoding: 'binary'
  region:
    type: "cat"
    cleaning: 'remove_nans'
    encoding: 'one_hot'
  bmi:
    type: "cont"
    cleaning: ['remove_nans', 'remove_outliers']
    scaling: 'min_max'
  children:
    type: "cont"
    cleaning: 'remove_nans'
  smoker:
    type: "cat"
    cleaning: 'remove_nans'
    encoding: 'ordinal'

dataset:
  split:
    stratified: no
    train: 80
    test: 20
    val: 10

model:
  regression:
    gradient_boosting:
      n_estimators: 100
      learning_rate: 0.1
      max_depth: 3
      min_samples_split: 2
      loss: 'squared_error'
      random_state: 42

score: ['r2', 'mae', 'r2', 'mape', 'rmse']

output_folder: "C:/Users/guilh/Documents/Projets_Code/yaml-ML/out/multiple"
name: "cfg8"