logs: no

loading:
  folder: "C:/Users/guilh/Documents/Projets_Code/yaml-ML/datasets"
  name: "insurance_charges"
  format: 'csv'
  separator: ','
#  folder: "path/to/dataset/folder"  # change it to the actual path to the folder in your machine

target_var: 'charges'

preprocessing:
  charges:
    type: "cont"
    cleaning: ['remove_nans', 'remove_outliers']
    replace_nans: 'median'
  age:
    type: "cont"
    cleaning: ['remove_nans', 'remove_outliers']
    replace_nans: 'median'
    scaling: 'abs_max'
  sex:
    type: "cat"
    cleaning: 'remove_nans'
    encoding: 'binary'
  region:
    type: "cat"
    cleaning: 'remove_nans'
    encoding: 'one_hot'
  bmi:
    type: "cont"
    cleaning: ['remove_nans', 'remove_outliers']
    scaling: 'standard'
  children:
    type: "cont"
    cleaning: 'remove_nans'
  smoker:
    type: "cat"
    cleaning: 'remove_nans'
    encoding: 'ordinal'

dataset:
  split:
    stratified: no
    train: 80
    test: 20
    val: 10

model:
  regression:
    catboost:
      iterations: 500
      depth: 6
      learning_rate: 0.1
#      lgbm:
#        max_depth: 4
#        learning_rate: 0.1
#        n_estimators: 100
#    lasso:
#      alpha: 0.1
#      fit_intercept: yes
#    mlp:
#      hidden_layer_sizes: [50, 50]
#      activation: 'relu'
#      solver: 'adam'
#      max_iter: 10000
#      random_state: 42
#    svr:
#      kernel: 'rbf'
#      C: 10
#      epsilon: 0.1

score: ['r2', 'mae', 'mape', 'rmse']

output_folder: "C:/Users/guilh/Documents/Projets_Code/yaml-ML/out"
name: "regression_example"